#!/usr/bin/env vim

NUM_GPUS: 2 # how many gups to use
LOG_PERIOD: 10 # log period
DATASET_NAME: 'charades' # name of dataset

MODEL:
  CLASSIFICATION_TYPE: 'ml' # either multi-label 'ml' or single-label 'sl'
  N_CLASSES: 157 # how many classes as output
  N_CHANNEL_GROUPS: 4 # how many channel groups
  #N_TC_LAYERS: 3 # number of timeception layers
  N_TC_TIMESTEPS: 32 # how mant timesteps expected as input to the timeception layers
  #N_INPUT_TIMESTEPS: 512 # how many timesteps (i.e. frames) expected as an input to the backbone CNN
  NAME: 'charades_assemblenet_plus_lite' # name suffex for the model to be trained
  BACKBONE_CNN: 'assemblenet_plus_lite'# which backbone cnn is used
  BACKBONE_FEATURE: 'mixed_5c' # type of feature output from backbone cnn
  MULTISCALE_TYPE: 'dl' # use multi-scale by dilation rate "dl" or multi-scale by kernel-size "ks"

TRAIN:
  BATCH_SIZE: 8 # batch size for training
  N_EPOCHS: 1000 # how many training epochs
  SCHEME: 'tco' # either 'ete' (end-to-end) or 'tco' ('timeception-only')
  N_WORKERS: 10 # how many parallel workers in the data generator

TEST:
  BATCH_SIZE: 8
  N_SAMPLES: 32

SOLVER:
  NAME: 'SGD'
  LR: 0.29
  ADAM_EPSILON: 0.0001
  SGD_WEIGHT_DECAY: 0.0001
  SGD_MOMENTUM: 0.9
  SGD_NESTEROV: True